    name: CI/CD
    on: 
        push:
            branches: [ feature ]
        pull_request:
            branches: [ feature ]
    jobs:
        build:
            runs-on: ubuntu-latest
            steps:
              - name: Setup Node.js environment
                uses: actions/setup-node@v4.0.1
                with:
                  node-version: "18.x"
              - name: front-end build
                run: |
                  pwd
                  
                  npm install
                  npm run build
                  echo "front end build success"
              - name: Setup .NET Core SDK
                uses: actions/setup-dotnet@v4.0.0
                with:
                  dotnet-version: "6"
              - name: back-end build
                run: |
                  cd backEnd
                  dotnet restore
                  dotnet build
                  echo "back end build success"
